name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  JAVA_VERSION: "17"
  DISTRIBUTION: "temurin"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Run Tests with Maven
        run: mvn test --file pom.xml

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "Connecting to Docker Hub... Command: docker login"
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" docker.io

      - name: Publish to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup docker-compose
        run: |
          sudo apt install docker-compose
      - name: Setup ssh
        run: |
          if [ ! -d ~/.ssh ]; then
            mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          fi
          printf '%s\n' "${{ secrets.DOCKER_HOST_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          printf '%s\n' "${{ secrets.DOCKER_HOST_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa
          echo "Add known hosts"
          sudo ssh-keyscan -p 22 "${{ secrets.DOCKER_HOST_ADDRESS }}" >> ~/.ssh/known_hosts

      - name: Docker Login
        run: |
          echo "Connecting to Docker Hub... Command: docker login"
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" docker.io
      - name: Docker Compose Up
        run: |
          docker-compose --host=ssh://root@${{ secrets.DOCKER_HOST_ADDRESS }}  -f docker-compose.yaml pull
          docker-compose --host=ssh://root@${{ secrets.DOCKER_HOST_ADDRESS }} -f docker-compose.yaml  up -d
